# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pjpauwels.gent
title: PJPauwels
email: pieterjanpauwels@gmail.com
author: Pieter-Jan Pauwels
description: > # "Write an awesome description for your new site here. 
  Hi I’m Pieter-Jan, I’m a twenty something from Ghent who’s captured by the idea of social innovation and how we can all co-create a better future in the open space. I also like turtles.  

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    logo: envelope
    url: mailto:hello@pjpauwels.gent
  - title: twitter
    logo: twitter
    url: https://twitter.com/PJPauwels
  - title: linkedin
    logo: linkedin
    url: https://www.linkedin.com/in/pjpauwels
