# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pjpauwels.gent
title: PJPauwels
email: hello@PJPauwels.gent
author: Pieter-Jan Pauwels
description: I am a social worker with a heart for communication and a brain for technology. Trying to bring both aspects together in a sustainable way through the different open communities. If you have questions about open data and open knowledge, I’m always up for a coffee.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/PJPauwels
  - title: github
    url: https://github.com/PieterJanPauwels
  - title: linkedin
    url: https://www.linkedin.com/in/pjpauwels
