# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pjpauwels.gent
title: PJPauwels
email: pieterjanpauwels@gmail.com
author: Pieter-Jan Pauwels
description: > # "Hi I’m Pieter-Jan, I’m a twenty something from Ghent who’s captured by the idea of open innovation and how we can all co-create a better future in the online space. I also like turtles."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    logo: envelope
    url: mailto:pieterjanpauwels@gmail.com
  - title: twitter
    logo: twitter
    url: https://twitter.com/PJPauwels
  - title: linkedin
    logo: linkedin
    url: https://www.linkedin.com/in/pjpauwels
  - title: github
    logo: github
    url: https://github.com/PieterJanPauwels
